// Curriculum safety gate for Lumora content. This module validates structure;
// it never turns prototype content into approved curriculum.

const ALLOWED_DIFFICULTIES = new Set(["intro", "practice", "challenge", "boss"]);
const SUPPORTED_MECHANICS = new Set(["collect", "match", "bridge", "path", "subtract", "sort", "shape", "rune", "restore", "route", "scenario", "mixed", "challenge", "boss"]);
const REQUIRED_TEXT_FIELDS = ["id", "subject", "domain", "skillId", "skillNameVi", "objectiveVi", "sourceReference"];

const isText = (value) => typeof value === "string" && value.trim().length > 0;
const asArray = (value) => (Array.isArray(value) ? value : []);
const isPrototypeSource = (value) => typeof value === "string" && /prototype|chưa được phê duyệt/i.test(value);
const isPlaceholderSource = (value) => typeof value !== "string" || /prototype|chưa được phê duyệt|\btbd\b|\btodo\b|placeholder|ai[- ]generated|generated by ai|^x$/i.test(value.trim());
const issue = (code, message, field, nodeId) => ({ code, message, field, nodeId: nodeId ?? null });

export class CurriculumReleaseError extends Error {
  constructor(audit) {
    super(`Curriculum release blocked by ${audit.errors.length} validation error(s).`);
    this.name = "CurriculumReleaseError";
    this.code = "CURRICULUM_RELEASE_BLOCKED";
    this.audit = structuredClone(audit);
  }
}

export function validateCurriculumNode(node, { mode = "prototype" } = {}) {
  const releaseMode = mode === "production";
  const nodeId = isText(node?.id) ? node.id.trim() : null;
  const errors = [];
  const warnings = [];
  if (!node || typeof node !== "object" || Array.isArray(node)) {
    errors.push(issue("NODE_INVALID", "Node must be an object.", null, nodeId));
    return { nodeId, valid: false, errors, warnings };
  }

  for (const field of REQUIRED_TEXT_FIELDS) {
    if (!isText(node[field])) errors.push(issue("FIELD_REQUIRED", `${field} must be a non-empty string.`, field, nodeId));
  }
  if (!Number.isInteger(node.grade) || node.grade < 1 || node.grade > 12) {
    errors.push(issue("GRADE_INVALID", "grade must be an integer from 1 to 12.", "grade", nodeId));
  }
  if (!Array.isArray(node.prerequisites) || node.prerequisites.some((value) => !isText(value))) {
    errors.push(issue("PREREQUISITES_INVALID", "prerequisites must be an array of non-empty node ids.", "prerequisites", nodeId));
  }
  if (!ALLOWED_DIFFICULTIES.has(node.difficulty)) {
    errors.push(issue("DIFFICULTY_INVALID", "difficulty must be intro, practice, challenge, or boss.", "difficulty", nodeId));
  }
  if (!Array.isArray(node.gameplayTemplates) || node.gameplayTemplates.length === 0 || node.gameplayTemplates.some((value) => !isText(value))) {
    errors.push(issue("GAMEPLAY_TEMPLATES_INVALID", "gameplayTemplates must contain at least one non-empty template id.", "gameplayTemplates", nodeId));
  }
  if (!SUPPORTED_MECHANICS.has(node.type)) {
    errors.push(issue("MECHANIC_UNSUPPORTED", "type must reference a supported runtime mechanic.", "type", nodeId));
  }
  if (Array.isArray(node.gameplayTemplates)) {
    if (node.gameplayTemplates.some((value) => !SUPPORTED_MECHANICS.has(value))) {
      errors.push(issue("TEMPLATE_UNSUPPORTED", "Every gameplay template must reference a supported runtime mechanic.", "gameplayTemplates", nodeId));
    }
    if (SUPPORTED_MECHANICS.has(node.type) && !node.gameplayTemplates.includes(node.type)) {
      errors.push(issue("TEMPLATE_TYPE_MISMATCH", "gameplayTemplates must include the node's runtime type.", "gameplayTemplates", nodeId));
    }
  }
  if (typeof node.approved !== "boolean") {
    errors.push(issue("APPROVAL_INVALID", "approved must be an explicit boolean.", "approved", nodeId));
  }

  if (releaseMode) {
    if (node.approved !== true) errors.push(issue("NOT_APPROVED", "Content has not been human-approved for production.", "approved", nodeId));
    if (!isText(node.sourceReference) || isPlaceholderSource(node.sourceReference)) {
      errors.push(issue("SOURCE_NOT_OFFICIAL", "Production content requires a specific reviewed curriculum source.", "sourceReference", nodeId));
    }
    const evidence = node.sourceEvidence;
    const evidenceValid = evidence && typeof evidence === "object" && !Array.isArray(evidence)
      && evidence.kind === "official-curriculum"
      && isText(evidence.documentId)
      && isText(evidence.revision)
      && isText(evidence.reviewedBy)
      && typeof evidence.reviewedAt === "string"
      && Number.isFinite(Date.parse(evidence.reviewedAt));
    if (!evidenceValid) {
      errors.push(issue("SOURCE_EVIDENCE_REQUIRED", "Production content requires official document id/revision and human review evidence.", "sourceEvidence", nodeId));
    }
  } else {
    if (node.approved !== true) warnings.push(issue("PROTOTYPE_UNAPPROVED", "Prototype content is intentionally not production-approved.", "approved", nodeId));
    if (isPrototypeSource(node.sourceReference)) warnings.push(issue("PROTOTYPE_SOURCE", "Source reference is a prototype placeholder.", "sourceReference", nodeId));
  }

  return { nodeId, valid: errors.length === 0, errors, warnings };
}

export function auditCurriculum(nodeDefinitions, { mode = "prototype", externalPrerequisiteIds = [] } = {}) {
  const input = Array.isArray(nodeDefinitions) ? nodeDefinitions : [];
  const externalIds = new Set(asArray(externalPrerequisiteIds).filter(isText).map((id) => id.trim()));
  const nodeAudits = input.map((node) => validateCurriculumNode(node, { mode }));
  const errors = nodeAudits.flatMap((entry) => entry.errors.map((item) => ({ ...item })));
  const warnings = nodeAudits.flatMap((entry) => entry.warnings.map((item) => ({ ...item })));
  if (!Array.isArray(nodeDefinitions)) errors.push(issue("COLLECTION_INVALID", "Curriculum must be an array.", null, null));
  if (input.length === 0) errors.push(issue("COLLECTION_EMPTY", "Curriculum must contain at least one node.", null, null));

  const firstIndexById = new Map();
  const firstIndexBySkill = new Map();
  input.forEach((node, index) => {
    if (isText(node?.id)) {
      const id = node.id.trim();
      if (firstIndexById.has(id)) errors.push(issue("DUPLICATE_NODE_ID", `Duplicate node id: ${id}.`, "id", id));
      else firstIndexById.set(id, index);
    }
    if (isText(node?.skillId)) {
      const skillId = node.skillId.trim();
      if (firstIndexBySkill.has(skillId)) errors.push(issue("DUPLICATE_SKILL_ID", `Duplicate skill id: ${skillId}.`, "skillId", node?.id));
      else firstIndexBySkill.set(skillId, index);
    }
  });
  input.forEach((node, index) => {
    if (!Array.isArray(node?.prerequisites)) return;
    for (const prerequisite of node.prerequisites) {
      if (!isText(prerequisite)) continue;
      const prerequisiteIndex = firstIndexById.get(prerequisite.trim());
      if (prerequisiteIndex === undefined) {
        if (!externalIds.has(prerequisite.trim())) {
          errors.push(issue("PREREQUISITE_UNKNOWN", `Unknown prerequisite: ${prerequisite}.`, "prerequisites", node?.id));
        }
      } else if (prerequisiteIndex >= index) {
        errors.push(issue("PREREQUISITE_ORDER", `Prerequisite ${prerequisite} must occur before ${node?.id ?? "this node"}.`, "prerequisites", node?.id));
      }
    }
  });

  return {
    mode: mode === "production" ? "production" : "prototype",
    valid: errors.length === 0,
    nodeCount: input.length,
    approvedCount: input.filter((node) => node?.approved === true).length,
    errors,
    warnings,
    nodes: nodeAudits.map((entry) => structuredClone(entry)),
  };
}

export function mergeCurriculumAudits(...audits) {
  const entries = audits.filter((audit) => audit && typeof audit === "object");
  return {
    mode: entries.some((audit) => audit.mode === "production") ? "production" : "prototype",
    valid: entries.length > 0 && entries.every((audit) => audit.valid === true),
    nodeCount: entries.reduce((total, audit) => total + (Number.isInteger(audit.nodeCount) ? audit.nodeCount : 0), 0),
    approvedCount: entries.reduce((total, audit) => total + (Number.isInteger(audit.approvedCount) ? audit.approvedCount : 0), 0),
    errors: entries.flatMap((audit) => Array.isArray(audit.errors) ? audit.errors.map((entry) => ({ ...entry })) : []),
    warnings: entries.flatMap((audit) => Array.isArray(audit.warnings) ? audit.warnings.map((entry) => ({ ...entry })) : []),
    nodes: entries.flatMap((audit) => Array.isArray(audit.nodes) ? audit.nodes.map((entry) => structuredClone(entry)) : []),
  };
}

export function assertProductionCurriculum(nodeDefinitions) {
  const audit = auditCurriculum(nodeDefinitions, { mode: "production" });
  if (!audit.valid) throw new CurriculumReleaseError(audit);
  return audit;
}
