export const worldName = "Rừng Thức Tỉnh";
export const defaultWorldId = "forest-awakening";

export const nubiEvolutionStages = [
  {
    stage: 1,
    id: "seed-light",
    name: "Mầm Sáng",
    sprite: "/assets/nubi-transparent-v3.png",
    description: "Nubi vừa thức tỉnh, mang ba dải cảm giác và Lõi Tri Thức đầu tiên.",
    traits: ["Ba dải cảm giác", "Lõi Tri Thức sơ khai", "Ánh sáng dịu"],
  },
  {
    stage: 2,
    id: "guiding-light",
    name: "Dẫn Quang",
    sprite: "/assets/nubi-evolved-v2.png",
    description: "Mastery của Rừng Thức Tỉnh làm Lõi Tri Thức mở rộng, rune chạy dọc cơ thể và hai vây sáng xuất hiện.",
    traits: ["Lõi hai tầng", "Rune mastery", "Vây Dẫn Quang"],
  },
];

const prototypeSource = "Prototype Lớp 1 — chưa được phê duyệt curriculum production";

const nodeDefinitions = [
  {
    id: "collect",
    index: 1,
    title: "Bãi Hạt Sáng",
    shortTitle: "Đếm ánh sáng",
    type: "collect",
    icon: "✦",
    chapter: "Mầm 1 · Tín hiệu đầu tiên",
    grade: 1,
    subject: "Toán",
    domain: "Số và phép tính",
    skillId: "MATH_G1_COUNT_WITHIN_10",
    skillNameVi: "Đếm số lượng",
    objectiveVi: "Nhận biết và đếm số lượng trong phạm vi 10.",
    prompt: "Chạm đủ 5 hạt đang phát sáng.",
    reward: 3,
    approved: false,
    sourceReference: prototypeSource,
    scene: "/assets/collect-scene.jpg",
    position: { x: 14, y: 69 },
  },
  {
    id: "match",
    index: 2,
    title: "Cổng Ghép Đôi",
    shortTitle: "Ghép số",
    type: "match",
    icon: "◇",
    chapter: "Mầm 2 · Cánh cổng ngủ quên",
    grade: 1,
    subject: "Toán",
    domain: "Số và phép tính",
    skillId: "MATH_G1_MATCH_NUMERAL_QUANTITY",
    skillNameVi: "Ghép số với lượng",
    objectiveVi: "Ghép chữ số với nhóm đồ vật tương ứng.",
    prompt: "Nối mỗi con số với nhóm đom đóm bằng nhau.",
    reward: 3,
    approved: false,
    sourceReference: prototypeSource,
    scene: "/assets/collect-scene.jpg",
    position: { x: 27, y: 58 },
  },
  {
    id: "bridge",
    index: 3,
    title: "Cầu Ánh Sáng",
    shortTitle: "Xây cầu",
    type: "bridge",
    icon: "+",
    chapter: "Mầm 3 · Dòng chảy tri thức",
    grade: 1,
    subject: "Toán",
    domain: "Số và phép tính",
    skillId: "MATH_G1_ADD_VISUAL",
    skillNameVi: "Phép cộng trực quan",
    objectiveVi: "Hiểu phép cộng qua việc thêm vật thể vào một nhóm.",
    prompt: "Cầu có 4 nhịp. Thêm 3 tinh thể để đủ 7.",
    reward: 4,
    approved: false,
    sourceReference: prototypeSource,
    scene: "/assets/bridge-scene.jpg",
    position: { x: 39, y: 70 },
  },
  {
    id: "path",
    index: 4,
    title: "Đường Dẫn Quang",
    shortTitle: "Nối đường sáng",
    type: "path",
    icon: "➜",
    chapter: "Mầm 4 · Lối đi qua vực sương",
    grade: 1,
    subject: "Toán",
    domain: "Số và phép tính",
    skillId: "MATH_G1_ADD_ON_PATH",
    skillNameVi: "Phép cộng qua đường đi",
    objectiveVi: "Hiểu phép cộng bằng cách thêm các bước sáng trên đường đi.",
    prompt: "Đường đã có 4 bước. Nối thêm 2 bước để đến cổng.",
    reward: 4,
    approved: false,
    sourceReference: prototypeSource,
    scene: "/assets/bridge-scene.jpg",
    position: { x: 47, y: 72 },
  },
  {
    id: "subtract",
    index: 5,
    title: "Vườn Đom Đóm",
    shortTitle: "Bớt ánh sáng",
    type: "subtract",
    icon: "−",
    chapter: "Mầm 5 · Ánh sáng trở về tổ",
    grade: 1,
    subject: "Toán",
    domain: "Số và phép tính",
    skillId: "MATH_G1_SUBTRACT_VISUAL",
    skillNameVi: "Phép trừ trực quan",
    objectiveVi: "Hiểu phép trừ qua việc lấy bớt vật thể khỏi một nhóm.",
    prompt: "Đưa 2 trong 6 đom đóm về tổ để còn lại 4.",
    reward: 4,
    approved: false,
    sourceReference: prototypeSource,
    scene: "/assets/collect-scene.jpg",
    position: { x: 54, y: 58 },
  },
  {
    id: "sort",
    index: 6,
    title: "Suối Sắp Xếp",
    shortTitle: "Phân loại",
    type: "sort",
    icon: "↕",
    chapter: "Mầm 6 · Hai bờ của suối",
    grade: 1,
    subject: "Toán",
    domain: "So sánh",
    skillId: "MATH_G1_COMPARE_SIZE",
    skillNameVi: "So sánh kích thước",
    objectiveVi: "So sánh và phân loại vật theo kích thước.",
    prompt: "Đưa hạt nhỏ về bờ nông, hạt lớn về bờ sâu.",
    reward: 4,
    approved: false,
    sourceReference: prototypeSource,
    scene: "/assets/sorting-scene.jpg",
    position: { x: 60, y: 44 },
  },
  {
    id: "shape",
    index: 7,
    title: "Xưởng Hình Khối",
    shortTitle: "Ghép hình",
    type: "shape",
    icon: "△",
    chapter: "Mầm 7 · Cỗ máy cổ",
    grade: 1,
    subject: "Toán",
    domain: "Hình học",
    skillId: "MATH_G1_BASIC_SHAPES",
    skillNameVi: "Nhận biết hình phẳng",
    objectiveVi: "Nhận biết và ghép các hình phẳng cơ bản.",
    prompt: "Kéo ba mảnh hình vào khe để cỗ máy hoạt động.",
    reward: 4,
    approved: false,
    sourceReference: prototypeSource,
    scene: "/assets/shape-workshop.jpg",
    position: { x: 67, y: 62 },
  },
  {
    id: "rune",
    index: 8,
    title: "Đường Rune",
    shortTitle: "Tìm quy luật",
    type: "rune",
    icon: "⌁",
    chapter: "Mầm 8 · Dấu vết lặp lại",
    grade: 1,
    subject: "Toán",
    domain: "Tư duy logic",
    skillId: "MATH_G1_SIMPLE_PATTERN",
    skillNameVi: "Chuỗi quy luật",
    objectiveVi: "Nhận ra và tiếp tục một chuỗi quy luật đơn giản.",
    prompt: "Quan sát nhịp lặp rồi chọn rune tiếp theo.",
    reward: 5,
    approved: false,
    sourceReference: prototypeSource,
    scene: "/assets/rune-scene.jpg",
    position: { x: 72, y: 37 },
  },
  {
    id: "scenario",
    index: 9,
    title: "Bếp Dã Ngoại",
    shortTitle: "Chia đủ phần",
    type: "scenario",
    icon: "●",
    chapter: "Mầm 9 · Bạn bè trong rừng",
    grade: 1,
    subject: "Toán",
    domain: "Ứng dụng số lượng",
    skillId: "MATH_G1_QUANTITY_SCENARIO",
    skillNameVi: "Số lượng thực tế",
    objectiveVi: "Dùng số lượng trong một tình huống gần gũi.",
    prompt: "Chia đủ 2 phần cho Míu và 3 phần cho Tí.",
    reward: 5,
    approved: false,
    sourceReference: prototypeSource,
    scene: "/assets/sorting-scene.jpg",
    position: { x: 79, y: 61 },
  },
  {
    id: "mixed",
    index: 10,
    title: "Trạm Giao Cảm",
    shortTitle: "Ba mạch sáng",
    type: "mixed",
    icon: "✧",
    chapter: "Mầm 10 · Kết nối kỹ năng",
    grade: 1,
    subject: "Toán",
    domain: "Tổng hợp",
    skillId: "MATH_G1_MIXED_FOUNDATIONS",
    skillNameVi: "Kết hợp kỹ năng",
    objectiveVi: "Kết hợp đếm, thêm và nhận biết hình trong một chuỗi ngắn.",
    prompt: "Khôi phục lần lượt ba mạch tri thức.",
    reward: 6,
    approved: false,
    sourceReference: prototypeSource,
    scene: "/assets/rune-scene.jpg",
    position: { x: 87, y: 47 },
  },
  {
    id: "challenge",
    index: 11,
    title: "Hang Tia Sáng",
    shortTitle: "Thử thách",
    type: "challenge",
    icon: "✺",
    chapter: "Mầm 11 · Trước cửa hang",
    grade: 1,
    subject: "Toán",
    domain: "Tổng hợp",
    skillId: "MATH_G1_MIXED_CHALLENGE",
    skillNameVi: "Thử thách tổng hợp",
    objectiveVi: "Củng cố các kỹ năng chính trước thử thách cuối.",
    prompt: "Giữ bình tĩnh và mở ba khóa ánh sáng.",
    reward: 7,
    approved: false,
    sourceReference: prototypeSource,
    scene: "/assets/boss-scene.jpg",
    position: { x: 75, y: 22 },
  },
  {
    id: "boss",
    index: 12,
    title: "Kẻ Nuốt Con Số",
    shortTitle: "Phục hồi Lõi",
    type: "boss",
    icon: "◆",
    chapter: "Mầm 12 · Lõi Tri Thức",
    grade: 1,
    subject: "Toán",
    domain: "Tổng hợp",
    skillId: "MATH_G1_WORLD_MASTERY",
    skillNameVi: "Làm chủ Rừng Thức Tỉnh",
    objectiveVi: "Dùng những kỹ năng đã luyện để phục hồi Lõi Tri Thức.",
    prompt: "Hoàn thành ba pha để ánh sáng trở về.",
    reward: 12,
    approved: false,
    sourceReference: prototypeSource,
    scene: "/assets/boss-scene.jpg",
    position: { x: 89, y: 20 },
  },
];

const energyTypesByNode = Object.freeze({
  collect: ["logic"],
  match: ["logic"],
  bridge: ["logic"],
  path: ["logic"],
  subtract: ["logic"],
  sort: ["logic"],
  shape: ["discovery"],
  rune: ["discovery"],
  scenario: ["discovery"],
  mixed: ["logic", "mastery"],
  challenge: ["logic", "mastery"],
  boss: ["mastery"],
});

export const nodes = nodeDefinitions.map((node, index) => ({
  ...node,
  prerequisites: index === 0 ? [] : [nodeDefinitions[index - 1].id],
  difficulty: node.id === "boss" ? "boss" : index < 3 ? "intro" : index < 9 ? "practice" : "challenge",
  gameplayTemplates: [node.type],
  energyTypes: energyTypesByNode[node.id] ?? [],
  masteryEvents: ["attempt", "hint-requested", "support-used", "level-solved"],
}));

export const orderedNodeIds = nodes.map((node) => node.id);

export const optionalQuests = [
  {
    id: "firefly-pairs",
    kind: "side",
    title: "Vạt Cỏ Đom Đóm",
    shortTitle: "Hồi sinh vạt cỏ",
    chapter: "Nhiệm vụ phụ · Những người bạn lạc đàn",
    type: "restore",
    icon: "✣",
    skillId: "MATH_G1_MATCH_NUMERAL_QUANTITY",
    grade: 1,
    subject: "Toán",
    domain: "Số và phép tính",
    difficulty: "practice",
    gameplayTemplates: ["restore"],
    masteryEvents: ["attempt", "hint-requested", "support-used", "level-solved"],
    approved: false,
    sourceReference: prototypeSource,
    skillNameVi: "Ghép số với lượng",
    objectiveVi: "Củng cố ghép lượng phù hợp khi cân bằng hai nguồn sống cho đàn đom đóm.",
    prompt: "Cân bằng nước và ánh sáng để đàn đom đóm trở về.",
    prerequisites: ["match"],
    discoveryPrerequisites: [],
    sourceNodeId: "match",
    restorationScenarioId: "firefly-grove-restoration-v1",
    energyTypes: ["logic", "discovery"],
    rewardCosmeticId: "firefly-trail",
    scene: "/assets/collect-scene.jpg",
    position: { x: 29, y: 77 },
  },
  {
    id: "seed-ferry",
    kind: "side",
    title: "Bến Hạt Trôi",
    shortTitle: "Đưa hạt qua suối",
    chapter: "Nhiệm vụ phụ · Hai bờ bình yên",
    type: "route",
    icon: "❧",
    skillId: "MATH_G1_COMPARE_SIZE",
    grade: 1,
    subject: "Toán",
    domain: "So sánh",
    difficulty: "practice",
    gameplayTemplates: ["route"],
    masteryEvents: ["attempt", "hint-requested", "support-used", "level-solved"],
    approved: false,
    sourceReference: prototypeSource,
    skillNameVi: "So sánh kích thước",
    objectiveVi: "Củng cố so sánh và phân loại theo kích thước bằng cách dẫn hạt qua đúng tuyến.",
    prompt: "Dẫn hạt nhỏ về bờ nông và hạt lớn về bờ sâu.",
    prerequisites: ["sort"],
    discoveryPrerequisites: [],
    sourceNodeId: "sort",
    routeScenarioId: "seed-ferry-route-v1",
    energyTypes: ["logic", "discovery"],
    rewardCosmeticId: "river-ribbon",
    scene: "/assets/sorting-scene.jpg",
    position: { x: 54, y: 38 },
  },
  {
    id: "moon-rune",
    kind: "secret",
    title: "Lùm Cây Trăng Khuyết",
    shortTitle: "Ký ức dưới trăng",
    chapter: "Nhiệm vụ bí mật · Nhịp sáng bị giấu",
    type: "rune",
    icon: "☾",
    skillId: "MATH_G1_SIMPLE_PATTERN",
    grade: 1,
    subject: "Toán",
    domain: "Tư duy logic",
    difficulty: "challenge",
    gameplayTemplates: ["rune"],
    masteryEvents: ["attempt", "hint-requested", "support-used", "level-solved"],
    approved: false,
    sourceReference: prototypeSource,
    skillNameVi: "Chuỗi quy luật",
    objectiveVi: "Vận dụng quy luật lặp trong một dấu vết bí mật.",
    prompt: "Quan sát nhịp rune trong ánh trăng rồi tìm mảnh tiếp theo.",
    prerequisites: ["rune"],
    discoveryPrerequisites: ["shape", "rune"],
    sourceNodeId: "rune",
    energyTypes: ["discovery"],
    rewardCosmeticId: "moon-orbit",
    scene: "/assets/rune-scene.jpg",
    position: { x: 76, y: 28 },
  },
];

// Environmental Restoration prototype: the same size comparison skill now
// changes a small world state instead of repeating the source sorting board.
// The route is intentionally finite, deterministic and local-only.
export const resourceRouteScenarios = [
  {
    id: "seed-ferry-route-v1",
    mode: "side",
    worldId: defaultWorldId,
    questId: "seed-ferry",
    sourceNodeId: "source",
    title: "Bến Hạt Trôi",
    objectiveVi: "Dẫn từng hạt qua tuyến đúng để dòng suối sáng trở lại.",
    resources: [
      { id: "seed-small-a", label: "Hạt nhỏ 1", kind: "small", icon: "•" },
      { id: "seed-small-b", label: "Hạt nhỏ 2", kind: "small", icon: "•" },
      { id: "seed-large-a", label: "Hạt lớn 1", kind: "large", icon: "●" },
      { id: "seed-large-b", label: "Hạt lớn 2", kind: "large", icon: "●" },
    ],
    nodes: [
      { id: "source", label: "Bến hạt", role: "source", accepts: ["small", "large"], capacity: 4 },
      { id: "shallow-bank", label: "Bờ nông", role: "destination", accepts: ["small"], capacity: 2, icon: "◌" },
      { id: "deep-bank", label: "Bờ sâu", role: "destination", accepts: ["large"], capacity: 2, icon: "◉" },
    ],
    connections: [
      { from: "source", to: "shallow-bank" },
      { from: "source", to: "deep-bank" },
    ],
    constraints: { maxActions: 6, softTimeLimit: 45 },
  },
];

// Environmental Restoration prototype: two bounded variables make each
// action change the grove state instead of replaying a learned board.
export const environmentRestorationScenarios = [
  {
    id: "firefly-grove-restoration-v1",
    mode: "side",
    worldId: defaultWorldId,
    questId: "firefly-pairs",
    sourceNodeId: "match",
    title: "Vạt Cỏ Đom Đóm",
    objectiveVi: "Đưa nước và ánh sáng về vùng cân bằng để vạt cỏ hồi sinh.",
    variables: [
      { id: "water", label: "Nước", icon: "≈", min: 0, max: 3, initial: 1, target: 2 },
      { id: "light", label: "Ánh sáng", icon: "✦", min: 0, max: 3, initial: 2, target: 1 },
    ],
    actions: [
      { id: "rain-drop", label: "Gọi mưa nhẹ", icon: "◆", variableId: "water", delta: 1, maxUses: 2 },
      { id: "drain-channel", label: "Mở rãnh thoát", icon: "⌁", variableId: "water", delta: -1, maxUses: 2 },
      { id: "sun-ray", label: "Mở vòm sáng", icon: "☀", variableId: "light", delta: 1, maxUses: 2 },
      { id: "shade-leaf", label: "Hạ lá che", icon: "◌", variableId: "light", delta: -1, maxUses: 2 },
    ],
    constraints: { maxActions: 6, softTimeLimit: 45 },
    cityFeatureId: "restored-firefly-grove",
  },
];

export const cityRestorationFeatures = [
  {
    id: "restored-firefly-grove",
    questId: "firefly-pairs",
    title: "Vạt Cỏ Đom Đóm hồi sinh",
    description: "Nước và ánh sáng đã cân bằng; những đốm sáng nhỏ trở lại bên Nubi.",
    icon: "✣",
    projection: {
      visualCue: "firefly-grove",
      energyTypes: ["nature", "discovery"],
      dormantDescription: "Vạt cỏ còn tối; những đốm sáng đang chờ nước và ánh sáng cân bằng.",
      restoredDescription: "Đom đóm đã trở lại và tạo thành một vòng sáng nhỏ quanh thành phố.",
    },
  },
  {
    id: "restored-river-bank",
    questId: "seed-ferry",
    title: "Bờ Suối Hai Màu",
    description: "Hai bờ đã nhận đúng hạt và dòng suối giữ lại nhịp sáng mới.",
    icon: "≈",
    projection: {
      visualCue: "river-bank",
      energyTypes: ["logic", "nature"],
      dormantDescription: "Bờ suối chưa bắt được nhịp; các hạt giống vẫn chờ đúng tuyến.",
      restoredDescription: "Dòng suối giữ lại nhịp sáng mới, nối hai bờ thành một lối đi sống.",
    },
  },
];

export const optionalQuestIds = optionalQuests.map((quest) => quest.id);

export const worlds = [
  {
    id: defaultWorldId,
    name: worldName,
    chapter: "Chương 1",
    grade: 1,
    availability: "playable",
    description: "Khôi phục mười hai vùng ký ức và đánh thức Lõi Tri Thức đầu tiên.",
    nodeIds: orderedNodeIds,
    optionalQuestIds,
    bossNodeId: "boss",
    prerequisiteWorldId: null,
    mapAsset: "/assets/world-map.jpg",
  },
  {
    id: "grade-1-world-2",
    name: "Vùng Tri Thức Tiếp Theo",
    chapter: "Chương 2",
    grade: 1,
    availability: "preview",
    description: "Sẽ được thiết kế sau khi nội dung Lớp 1 có curriculum evidence và phê duyệt.",
    preview: {
      title: "Dòng Sông Pha Lê",
      kicker: "Bản thiết kế thế giới kế tiếp",
      description: "Một chân trời concept nơi dòng nước ghi nhớ lựa chọn của người giữ tri thức. Đây là lore và gameplay direction, chưa phải curriculum playable.",
      pillars: ["Môi trường phản hồi theo thao tác", "Puzzle dòng chảy và kết nối", "Linh Thú mở thêm dấu ấn ánh sáng"],
      gate: "Chỉ mở sau khi World hiện tại có curriculum evidence chính thức và được phê duyệt bởi con người.",
    },
    nodeIds: [],
    optionalQuestIds: [],
    bossNodeId: null,
    prerequisiteWorldId: defaultWorldId,
    mapAsset: null,
  },
];

export const cityBuildings = [
  { id: "logic", name: "Tháp Logic", unlockAt: 3, masteryRequirement: { nodeIds: ["collect", "match", "bridge"], minimum: 2 }, icon: "✦", district: "Khu Mạch Sáng", description: "Lưu lại cách con đếm, ghép số và dựng nhịp cầu đầu tiên.", rewardCosmeticId: "number-crown" },
  { id: "shapes", name: "Xưởng Hình Khối", unlockAt: 7, masteryRequirement: { nodeIds: ["collect", "match", "bridge", "path", "subtract", "sort", "shape"], minimum: 2 }, icon: "△", district: "Khu Chế Tác", description: "Biến những hình phẳng đã nhận biết thành dấu ấn bảo hộ cho Nubi.", rewardCosmeticId: "logic-shield" },
  { id: "observatory", name: "Đài Quan Sát", unlockAt: 9, masteryRequirement: { nodeIds: ["collect", "match", "bridge", "path", "subtract", "sort", "shape", "rune", "scenario"], minimum: 2 }, icon: "◉", district: "Khu Khám Phá", description: "Soi rõ quy luật và những con đường tri thức còn nằm phía trước.", rewardCosmeticId: "explorer-wings" },
  { id: "library", name: "Thư viện Ánh Sáng", unlockAt: 12, masteryRequirement: { nodeIds: ["collect", "match", "bridge", "path", "subtract", "sort", "shape", "rune", "scenario", "mixed", "challenge", "boss"], minimum: 2 }, icon: "▤", district: "Lõi Thành Phố", description: "Gom toàn bộ ký ức của Rừng Thức Tỉnh thành một nguồn sáng lâu dài.", rewardCosmeticId: "knowledge-staff" },
];

export const cityCosmetics = [
  { id: "number-crown", name: "Vương Miện Con Số", slot: "head", icon: "♢", unlock: { type: "building", buildingId: "logic" }, description: "Dấu ấn của những lượng đầu tiên đã được gọi tên." },
  { id: "logic-shield", name: "Khiên Logic", slot: "side", icon: "⬡", unlock: { type: "building", buildingId: "shapes" }, description: "Một lớp ánh sáng hình học, chỉ mang ý nghĩa thành tựu." },
  { id: "explorer-wings", name: "Cánh Khám Phá", slot: "back", icon: "⌁", unlock: { type: "building", buildingId: "observatory" }, description: "Đôi cánh ánh sáng cho những người thích tìm quy luật." },
  { id: "knowledge-staff", name: "Trượng Tri Thức", slot: "hand", icon: "⚚", unlock: { type: "building", buildingId: "library" }, description: "Kỷ vật hoàn thành Rừng Thức Tỉnh; không cộng sức mạnh học tập." },
  { id: "memory-orbit", name: "Quỹ Đạo Ký Ức", slot: "aura", icon: "✦", unlock: { type: "practice-sessions", count: 1 }, description: "Mở sau khi hoàn tất một Daily Adventure." },
  { id: "core-halo", name: "Hào Quang Lõi", slot: "aura", icon: "◌", unlock: { type: "nubi-stage", stage: 2 }, description: "Ánh sáng của hình thái Nubi đã tiến hóa." },
  { id: "firefly-trail", name: "Vệt Bay Đom Đóm", slot: "aura", icon: "✣", unlock: { type: "quest", questId: "firefly-pairs" }, description: "Dấu sáng của nhiệm vụ phụ đầu tiên; không cộng sức mạnh học tập." },
  { id: "river-ribbon", name: "Dải Lụa Dòng Suối", slot: "back", icon: "≈", unlock: { type: "quest", questId: "seed-ferry" }, description: "Một dải sáng ghi dấu cách con phân loại hai bờ." },
  { id: "moon-orbit", name: "Quỹ Đạo Trăng Khuyết", slot: "aura", icon: "☾", unlock: { type: "quest", questId: "moon-rune" }, description: "Kỷ vật bí mật của nhịp rune dưới trăng." },
];

export function getNextNode(progress) {
  return nodes.find((node) => !progress.completed.includes(node.id)) ?? nodes.at(-1);
}

export function getMasteryLabel(score = 0) {
  if (score >= 3) return "Tự làm vững vàng";
  if (score === 2) return "Hoàn thành có hỗ trợ";
  if (score === 1) return "Hoàn thành có hướng dẫn";
  return "Chưa có dữ liệu";
}
