import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const srcDir = path.dirname(fileURLToPath(import.meta.url));
const readSource = (name) => fs.readFileSync(path.join(srcDir, name), "utf8");

test("Nubi runtime keeps the transparent sprite grounded with layered depth cues", () => {
  const app = readSource("App.jsx");
  const css = readSource("styles.css");

  assert.match(app, /className="nubi-contact-shadow"/);
  assert.match(app, /className="nubi-character"/);
  assert.match(app, /className="nubi-silhouette"/);
  assert.match(app, /className="nubi-foreground-sparks"/);
  assert.match(app, /data-nubi-cutout="true"/);
  assert.match(app, /data-nubi-asset={evolutionStage\.sprite\.split\("\/"\)\.pop\(\)}/);
  assert.match(app, /style=\{\{ "--nubi-sprite": `url\(\$\{evolutionStage\.sprite\}\)` \}\}/);
  assert.match(app, /className="nubi-signal-corona"/);
  assert.match(app, /className="nubi-cutout-edge"/);
  assert.match(app, /data-nubi-surface="floating"/);
  assert.match(app, /className="play-nubi-stage"/);
  assert.match(app, /className="play-nubi-tether"/);
  assert.match(app, /className="daily-puzzle-nubi"><span className="daily-puzzle-orbit"[^>]* \/><span className="practice-nubi-tether"/);
  assert.match(app, /className="discovery-nubi"><span className="discovery-nubi-orbit"[^>]* \/><span className="practice-nubi-tether"/);
  assert.match(app, /<NubiFigure className="evolution-nubi"/);
  assert.match(css, /\.nubi-figure\s*\{[^}]*background:\s*transparent !important/s);
  assert.match(css, /\.nubi-character > img\s*\{[^}]*background:\s*transparent !important[^}]*background-image:\s*none !important/s);
  assert.match(css, /\.nubi-figure\s*\{[^}]*background:\s*transparent !important/s);
  assert.match(css, /\.nubi-signal-corona\s*\{[^}]*opacity:\s*0/);
  assert.match(css, /\.nubi-figure\[data-nubi-signal="responding"\] \.nubi-signal-corona/);
  assert.match(css, /\.nubi-figure\[data-nubi-signal="recovering"\] \.nubi-signal-corona/);
  assert.match(css, /@keyframes nubi-corona-open/);
  assert.match(css, /\.play-nubi-signal:has\(\.nubi-figure\[data-nubi-signal="responding"\]\)/);
  assert.match(css, /@keyframes nubi-signal-panel/);
  assert.match(css, /\.nubi-contact-shadow\s*\{/);
  assert.match(css, /\.nubi-silhouette\s*\{[^}]*mask-image:/s);
  assert.match(css, /\.nubi-contact-shadow\s*\{[^}]*bottom:\s*8%/s);
  assert.match(css, /\.nubi-contact-shadow\s*\{[^}]*radial-gradient\([^}]*radial-gradient/s);
  assert.match(css, /\.nubi-silhouette\s*\{[^}]*mix-blend-mode:\s*screen/s);
  assert.match(css, /\.nubi-figure \.nubi-silhouette\s*\{[^}]*opacity:\s*\.08/s);
  assert.match(css, /\.nubi-figure \.nubi-cutout-edge\s*\{[^}]*opacity:\s*\.14/s);
  assert.match(css, /\.nubi-character\s*\{[^}]*z-index:\s*3/s);
  assert.match(css, /\.nubi-figure\[data-nubi-core="ambient"\] \.nubi-core-flare\s*\{[^}]*opacity:\s*0[^}]*animation:\s*none/s);
  assert.match(css, /\.nubi-figure\[data-nubi-core="visible"\] \.nubi-core-flare\s*\{[^}]*opacity:\s*1/s);
  assert.match(css, /@keyframes nubi-foreground-spark/);
  assert.match(css, /\.nubi-figure\s*\{[^}]*perspective:/s);
  assert.match(css, /\.nubi-particle-field i:nth-child\(2\)/);
  assert.match(css, /@keyframes nubi-orbit-one\s*\{\s*0%\s*\{[^}]*rotateX/s);
  assert.match(app, /const homeNubiMood = progress\.nubiStage >= 2 \? "resonant"/);
  assert.match(app, /<NubiFigure className="home-nubi-figure"[^>]+mood=\{homeNubiMood\}[^>]+energyTypes=\{homeNubiEnergyTypes\}/);
  assert.match(css, /\.nubi-hero:hover > \.nubi-figure, \.nubi-hero:focus-visible > \.nubi-figure/);
  assert.match(css, /\.nubi-hero:focus-visible\s*\{[^}]*outline:/s);
  assert.match(css, /\.play-nubi-signal\s*\{[^}]*min-height:\s*148px[^}]*background:\s*transparent/s);
  assert.match(css, /\.play-nubi-stage\s*\{[^}]*width:\s*138px[^}]*height:\s*148px/s);
  assert.match(css, /\.play-nubi-signal \.play-nubi-figure\s*\{[^}]*width:\s*142px[^}]*height:\s*142px/s);
  assert.match(css, /\.play-nubi-copy\s*\{[^}]*background:/s);
  assert.match(css, /\.play-nubi-tether\s*\{[^}]*opacity:\s*0/);
  assert.match(css, /\.play-view:has\(\.game-board \[data-drop-zone\]\[data-drag-hover="true"\]\) \.play-nubi-tether/);
  assert.match(css, /\.practice-nubi-tether\s*\{[^}]*opacity:\s*0/);
  assert.match(css, /\.practice-puzzle-view:has\(\.daily-weave-board \[data-drop-zone\]\[data-drag-hover="true"\]\) \.practice-nubi-tether/);
  assert.match(css, /\.practice-discovery-view:has\(\.discovery-board \[data-drop-zone\]\[data-drag-hover="true"\]\) \.practice-nubi-tether/);
  assert.match(css, /@keyframes nubi-drop-tether/);
  assert.match(css, /\.play-nubi-signal::before\s*\{[^}]*radial-gradient/s);
  assert.match(css, /\.play-nubi-signal::before\s*\{[^}]*background:\s*transparent[^}]*filter:\s*none/s);
  assert.match(css, /\.nubi-figure\[data-nubi-core="ambient"\] \.nubi-energy-field::before\s*\{[^}]*opacity:\s*\.3[^}]*animation:\s*none/s);
  assert.match(css, /\.play-view:has\(\.drag-token\.dragging\) \.play-nubi-figure \.nubi-signal-corona/);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.nubi-figure \.nubi-signal-beam[\s\S]*opacity:\s*0 !important/s);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.nubi-signal-corona[\s\S]*animation:\s*none !important/s);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.play-nubi-signal:has\(\.nubi-figure\[data-nubi-signal="responding"\]\)/s);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.play-nubi-tether/);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.practice-nubi-tether/);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.nubi-figure \.nubi-resonance-ribbons[\s\S]*animation:\s*none !important/s);
  assert.match(css, /\.restore-nubi\s*\{[^}]*pointer-events:\s*none/);
  assert.match(css, /\.city-nubi-stage > \.nubi-figure\s*\{[^}]*inset:\s*4% 0 17%/);
  assert.match(css, /@media \(max-width:\s*840px\)[\s\S]*\.restore-card\s*\{[^}]*margin:\s*390px 0 0/s);
  assert.match(css, /@media \(max-width:\s*840px\)[\s\S]*\.practice-nubi-wrap\s*\{[^}]*bottom:\s*8px/s);
  assert.match(css, /@media \(max-width:\s*840px\)[\s\S]*\.daily-puzzle-nubi\s*\{[^}]*bottom:\s*18px/s);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.evolution-before\s*\{[^}]*opacity:\s*0 !important/s);
  assert.match(css, /@media \(max-width:\s*560px\)[\s\S]*\.nubi-hero\s*\{[^}]*top:\s*28px[^}]*right:\s*5%[^}]*width:\s*min\(310px,88%\)/s);
  assert.match(css, /@media \(max-width:\s*560px\)[\s\S]*\.nubi-hero:focus-visible\s*\{[^}]*outline-offset:\s*2px/s);
  assert.match(css, /@media \(max-width:\s*560px\)[\s\S]*\.nubi-hero > \.nubi-figure \.nubi-resonance-ribbons\s*\{[^}]*inset:\s*1% 2%/s);
  assert.match(css, /\.play-view:has\(\.drag-token\.dragging\) \.play-nubi-figure/);
  assert.match(css, /@keyframes nubi-drag-attention/);
  assert.match(app, /const \[awakeningStarted, setAwakeningStarted\] = useState\(false\)/);
  assert.match(app, /const \[awakeningSignal, setAwakeningSignal\] = useState\(createNubiSignalState\)/);
  assert.match(app, /const awakeningStartedRef = useRef\(false\)/);
  assert.match(app, /if \(awakeningStartedRef\.current\) return/);
  assert.match(app, /transitionNubiSignal\(current, \{ type: "level-success" \}\)/);
  assert.match(app, /window\.setTimeout\(\(\) => \{[\s\S]*onFinish\(\{ alias, ageBand \}\)/s);
  assert.match(app, /window\.clearTimeout\(awakeningTimerRef\.current\)/);
  assert.match(app, /<NubiFigure className="awakening-nubi"[^>]+mood=\{awakeningStarted \? "resonant" : "curious"\}[^>]+energyTypes=\{\["discovery"\]\}[^>]+signalState=\{awakeningSignal\}/);
  assert.match(app, /className=\{`awakening-shard \$\{awakeningStarted \? "is-awakened" : ""\}`\}/);
  assert.match(app, /disabled=\{awakeningStarted\}/);
  assert.match(css, /\.awakening-nubi\s*\{[^}]*isolation:\s*isolate[^}]*drop-shadow/s);
  assert.match(css, /\.awakening-nubi::before\s*\{[^}]*radial-gradient/s);
  assert.match(css, /\.awakening-nubi::after\s*\{[^}]*border-color:/s);
  assert.match(css, /\.awakening-nubi\[data-nubi-signal="resonant"\]\s*\{[^}]*animation:\s*nubi-awaken/s);
  assert.match(css, /\.awakening-shard\.is-awakened\s*\{[^}]*animation:\s*shard-awakened/s);
  assert.match(css, /@keyframes awakening-aura-breathe/);
  assert.match(css, /@keyframes awakening-ring-orbit/);
  assert.match(css, /@keyframes shard-release/);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.awakening-nubi::before[\s\S]*\.awakening-shard \{ animation: none !important; \}/s);
  assert.match(app, /const practiceEnergyTypes = \[\.\.\.new Set\(queueNodes\.flatMap/);
  assert.match(app, /<NubiFigure stage=\{stage\} mood=\{challengeCount > 0 \? "curious" : "idle"\} energyTypes=\{practiceEnergyTypes\}/);
  assert.match(app, /const dailyEnergyTypes = \[\.\.\.new Set\(challenge\.tokens\.map/);
  assert.match(app, /<NubiFigure stage=\{stage\} mood=\{oracleMood\} energyTypes=\{dailyEnergyTypes\}/);
  assert.match(app, /const discoveryEnergyTypes = \[\.\.\.new Set\(\(challenge\?\.fragments \?\? \[\]\)\.flatMap/);
  assert.match(app, /<NubiFigure stage=\{stage\} mood=\{oracleMood\} energyTypes=\{discoveryEnergyTypes\}/);
  assert.doesNotMatch(app, /nubi-hero-v2\.png/);
});
